version: '3.8'

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/simple-mern-backend:latest
    container_name: mern-backend-prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/mern-app
    depends_on:
      - mongodb
    ports:
      - '5000:5000'
    networks:
      - mern-network

  frontend:
    image: ${DOCKERHUB_USERNAME}/simple-mern-frontend:latest
    container_name: mern-frontend-prod
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - mern-network

  mongodb:
    image: mongo:latest
    container_name: mongodb-prod
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
