apiVersion: v1
kind: ConfigMap
metadata:
  name: mern-config
  namespace: mern-app
data:
  NODE_ENV: 'production'
  MONGODB_URI: 'mongodb://mongodb-0.mongodb:27017/mern-app'
  PORT: '5000'
  MONGO_DATA_DIR: '/data/db'
