apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mern-app
type: Opaque
data:
  # These are example values, you should replace them with your own base64 encoded values
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4= # admin
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ= # password
