name: Deploy to Production

on:
  workflow_run:
    workflows: ['Docker Build and Push']
    types:
      - completed
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" > .env

      - name: Deploy with docker-compose
        run: |
          docker-compose -f docker-compose.prod.yml pull
          docker-compose -f docker-compose.prod.yml up -d

      - name: Verify deployment
        run: |
          docker-compose -f docker-compose.prod.yml ps
          echo "Deployment completed successfully!"
